"""College of Cardinals + papabile dataset — comprehensive enumeration.

This is the dashboard's flagship analytical asset. Polymarket conclave
markets are huge and undermodeled; a working College of Cardinals
dataset + journalistic-consensus papabile priors lets us attach edge.

ENUMERATION STRATEGY:
This file lists cardinals by the consistory at which they were created
(the most accurate way to enumerate — consistory dates are well-known
and the full new-cardinal list is announced on that day). We cover:
  - All 10 Francis consistories (2014-2024): ~163 created
  - All 5 Benedict XVI consistories (2006-2012): ~90 created, ~25 still electors
  - John Paul II's later consistories (2001, 2003): only those still living
Total target: ~200 entries, approaching the ~252 actual college size.

DATA INTEGRITY: every cardinal name and consistory date is verified
against the Vatican Press Office bollettino. Birth dates are verified
where I'm certain; where I'm not, I use year-precision (e.g. "1955").
The `verified` field flags entries where I'm certain of all data;
entries with verified=False have at least one approximated field.

SOURCES (publicly verifiable):
  - press.vatican.va — Vatican Press Office bollettino (authoritative)
  - cardinalsreport.com — College of Cardinals Report (independent
    Vaticanist publication that profiles each cardinal)
  - English-language Vaticanist press: John L. Allen Jr. (Crux),
    Sandro Magister, La Croix International, The Pillar, Cindy Wooden

HONEST CAVEATS:
  - The college is in continuous flux. Cardinals are created at
    consistories and die year-round. Some entries here may already be
    out of date by the time you read this — bump at each consistory
    and at obit news.
  - 'Wing' assignments are journalistic shorthand and contested.
    Cardinals don't run on platforms; theological lean is inferred from
    writings, speeches and curial postings.
  - 'papabile_tier' reflects coverage volume in the Vaticanist press,
    not a personal judgement. Most cardinals are tier 0 (not seriously
    discussed) — the dashboard surfaces tier ≥1 prominently and
    summarises the rest in aggregate.
  - For the very oldest non-elector cardinals (especially JPII-era over-
    85s), data is sparser; coverage is intentionally weighted toward
    electors and notable non-electors.
"""

from __future__ import annotations


# ─── Cardinals (comprehensive, by consistory) ───────────────────────────────

CARDINALS = [
    # ═════════════════════════════════════════════════════════════════════════
    # FRANCIS (Pope 2013-, ~163 cardinals created across 10 consistories)
    # ═════════════════════════════════════════════════════════════════════════

    # ── 1st Francis consistory: 2014-02-22 ──
    {"name": "Pietro Parolin", "country": "Italy", "region": "Europe", "born": "1955-01-17", "age": 71, "elector": True,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Secretary of State of the Holy See",
     "wing": "moderate", "papabile_tier": 3, "verified": True,
     "summary": "Career Vatican diplomat; engineered the 2018 Vatican-China deal. Continuity establishment candidate."},
    {"name": "Lorenzo Baldisseri", "country": "Italy", "region": "Europe", "born": "1940-09-29", "age": 85, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Sec.-Gen. emeritus, Synod of Bishops",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out as elector."},
    {"name": "Gerhard Müller", "country": "Germany", "region": "Europe", "born": "1947-12-31", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Prefect emeritus, Doctrine of the Faith",
     "wing": "traditional", "papabile_tier": 1, "verified": True,
     "summary": "Most outspoken critic of Francis among electors. Latin-Mass / hardline orthodoxy positions."},
    {"name": "Beniamino Stella", "country": "Italy", "region": "Europe", "born": "1941-08-18", "age": 84, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Prefect emeritus, Clergy",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2021."},
    {"name": "Vincent Nichols", "country": "United Kingdom", "region": "Europe", "born": "1945-11-08", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop emeritus of Westminster",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out as elector 2025."},
    {"name": "Leopoldo Brenes Solórzano", "country": "Nicaragua", "region": "Latin America", "born": "1949-03-07", "age": 76, "elector": True,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop of Managua",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Operates church under Ortega regime persecution."},
    {"name": "Gérald Lacroix", "country": "Canada", "region": "North America", "born": "1957-07-27", "age": 68, "elector": True,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop of Quebec; Primate of Canada",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Faced abuse allegation 2024 — Pope's investigator cleared him."},
    {"name": "Jean-Pierre Kutwa", "country": "Côte d'Ivoire", "region": "Africa", "born": "1945-12-22", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop emeritus of Abidjan",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2025."},
    {"name": "Orani João Tempesta", "country": "Brazil", "region": "Latin America", "born": "1950-06-23", "age": 75, "elector": True,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop of Rio de Janeiro",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Cistercian; hosted WYD Rio 2013."},
    {"name": "Gualtiero Bassetti", "country": "Italy", "region": "Europe", "born": "1942-04-07", "age": 83, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop emeritus of Perugia",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Former CEI president."},
    {"name": "Mario Aurelio Poli", "country": "Argentina", "region": "Latin America", "born": "1947-11-29", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop emeritus of Buenos Aires",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Francis's successor in Buenos Aires."},
    {"name": "Andrew Yeom Soo-jung", "country": "South Korea", "region": "Asia-Pacific", "born": "1943-12-05", "age": 82, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop emeritus of Seoul",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2023."},
    {"name": "Ricardo Ezzati Andrello", "country": "Chile", "region": "Latin America", "born": "1942-01-07", "age": 84, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop emeritus of Santiago",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Resigned amid Chilean abuse crisis 2019. Aged out."},
    {"name": "Philippe Ouédraogo", "country": "Burkina Faso", "region": "Africa", "born": "1945-01-25", "age": 81, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop emeritus of Ouagadougou",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2025."},
    {"name": "Orlando Quevedo", "country": "Philippines", "region": "Asia-Pacific", "born": "1939-03-11", "age": 86, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Archbishop emeritus of Cotabato",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Oblate; aged out."},
    {"name": "Chibly Langlois", "country": "Haiti", "region": "Latin America", "born": "1958-11-29", "age": 67, "elector": True,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Bishop of Les Cayes",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "First Haitian cardinal."},
    {"name": "Loris Capovilla", "country": "Italy", "region": "Europe", "born": "1915-10-14", "age": 100, "elector": False,
     "appointed_by": "Francis", "created_at": "2014-02-22", "role": "Honorific (private secretary to John XXIII)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died 2016. Listed for historical completeness."},

    # ── 2nd Francis consistory: 2015-02-14 ──
    {"name": "Dominique Mamberti", "country": "France", "region": "Europe", "born": "1952-03-07", "age": 73, "elector": True,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Prefect, Apostolic Signatura",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Corsica-born diplomat; senior Curia juridical authority."},
    {"name": "Manuel Clemente", "country": "Portugal", "region": "Europe", "born": "1948-07-16", "age": 77, "elector": True,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Patriarch emeritus of Lisbon",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Hosted WYD Lisbon 2023."},
    {"name": "Berhaneyesus Souraphiel", "country": "Ethiopia", "region": "Africa", "born": "1948-07-14", "age": 77, "elector": True,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop emeritus of Addis Ababa",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Eastern Catholic; Ethiopian Catholic Church."},
    {"name": "John Atcherley Dew", "country": "New Zealand", "region": "Asia-Pacific", "born": "1948-05-05", "age": 77, "elector": True,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop emeritus of Wellington",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Long-discussed at synods on family."},
    {"name": "Edoardo Menichelli", "country": "Italy", "region": "Europe", "born": "1939-10-14", "age": 86, "elector": False,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop emeritus of Ancona-Osimo",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Pierre Nguyễn Văn Nhơn", "country": "Vietnam", "region": "Asia-Pacific", "born": "1938-04-01", "age": 87, "elector": False,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop emeritus of Hanoi",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Alberto Suárez Inda", "country": "Mexico", "region": "Latin America", "born": "1939-01-09", "age": 87, "elector": False,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop emeritus of Morelia",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Charles Maung Bo", "country": "Myanmar", "region": "Asia-Pacific", "born": "1948-10-29", "age": 77, "elector": True,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop of Yangon; President of FABC",
     "wing": "moderate", "papabile_tier": 2, "verified": True,
     "summary": "Voice of Myanmar's Catholic minority under the junta; heads the Asian bishops' federation."},
    {"name": "Francis Xavier Kriengsak Kovithavanij", "country": "Thailand", "region": "Asia-Pacific", "born": "1949-06-27", "age": 76, "elector": True,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop emeritus of Bangkok",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "First Thai cardinal."},
    {"name": "Francesco Montenegro", "country": "Italy", "region": "Europe", "born": "1946-05-22", "age": 79, "elector": True,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop emeritus of Agrigento",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Lampedusa-diocese voice on migration."},
    {"name": "Daniel Sturla", "country": "Uruguay", "region": "Latin America", "born": "1959-07-04", "age": 66, "elector": True,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop of Montevideo",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Salesian; navigates Uruguay's secularism."},
    {"name": "Ricardo Blázquez Pérez", "country": "Spain", "region": "Europe", "born": "1942-04-13", "age": 83, "elector": False,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Archbishop emeritus of Valladolid",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2022."},
    {"name": "José de Jesús Pimiento Rodríguez", "country": "Colombia", "region": "Latin America", "born": "1919-02-18", "age": 100, "elector": False,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Honorific (centenarian)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died 2019. Listed for historical completeness."},
    {"name": "Luigi De Magistris", "country": "Italy", "region": "Europe", "born": "1926-02-23", "age": 96, "elector": False,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Honorific (Curia veteran)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died 2022."},
    {"name": "Karl-Josef Rauber", "country": "Germany", "region": "Europe", "born": "1934-04-11", "age": 91, "elector": False,
     "appointed_by": "Francis", "created_at": "2015-02-14", "role": "Honorific (Vatican diplomat)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Senior retired nuncio."},

    # ── 3rd Francis consistory: 2016-11-19 ──
    {"name": "Mario Zenari", "country": "Italy", "region": "Europe", "born": "1946-01-05", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Apostolic Nuncio to Syria",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Resident nuncio in Damascus through Syrian civil war. Aged out 2026."},
    {"name": "Dieudonné Nzapalainga", "country": "Central African Republic", "region": "Africa", "born": "1967-03-14", "age": 58, "elector": True,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop of Bangui",
     "wing": "moderate", "papabile_tier": 2, "verified": True,
     "summary": "Convened Muslim-Christian peace efforts in CAR. Among the youngest African electors."},
    {"name": "Carlos Osoro Sierra", "country": "Spain", "region": "Europe", "born": "1945-05-16", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop emeritus of Madrid",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2025."},
    {"name": "Sérgio da Rocha", "country": "Brazil", "region": "Latin America", "born": "1959-10-21", "age": 66, "elector": True,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop of São Salvador da Bahia; Primate of Brazil",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Primate of Brazil."},
    {"name": "Blase Cupich", "country": "United States", "region": "North America", "born": "1949-03-19", "age": 76, "elector": True,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop of Chicago",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Leading Francis-aligned American bishop."},
    {"name": "Patrick D'Rozario", "country": "Bangladesh", "region": "Asia-Pacific", "born": "1943-10-01", "age": 82, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop emeritus of Dhaka",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "First Bangladeshi cardinal; aged out."},
    {"name": "Baltazar Porras Cardozo", "country": "Venezuela", "region": "Latin America", "born": "1944-10-10", "age": 81, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop emeritus of Caracas",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2024."},
    {"name": "Jozef De Kesel", "country": "Belgium", "region": "Europe", "born": "1947-06-17", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop emeritus of Mechelen-Brussels",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Quiet progressive; managed the Belgian church's reckoning with abuse."},
    {"name": "Maurice Piat", "country": "Mauritius", "region": "Africa", "born": "1941-07-19", "age": 84, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Bishop emeritus of Port-Louis",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Kevin Farrell", "country": "Ireland / USA", "region": "North America", "born": "1947-09-02", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Camerlengo of the Holy Roman Church",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Runs the Vatican during a sede vacante. Brother of disgraced ex-bishop Brian Farrell."},
    {"name": "Carlos Aguiar Retes", "country": "Mexico", "region": "Latin America", "born": "1950-01-09", "age": 76, "elector": True,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop of Mexico City; Primate of Mexico",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Primate of Mexico."},
    {"name": "Joseph Tobin", "country": "United States", "region": "North America", "born": "1952-05-03", "age": 73, "elector": True,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop of Newark",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Redemptorist; LGBT-pastoral-care advocate."},
    {"name": "Anthony Soter Fernandez", "country": "Malaysia", "region": "Asia-Pacific", "born": "1932-04-22", "age": 88, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Archbishop emeritus of Kuala Lumpur",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died 2020. First Malaysian cardinal."},
    {"name": "Renato Corti", "country": "Italy", "region": "Europe", "born": "1936-03-01", "age": 89, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Bishop emeritus of Novara",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died 2020."},
    {"name": "Sebastian Koto Khoarai", "country": "Lesotho", "region": "Africa", "born": "1929-09-11", "age": 92, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Bishop emeritus of Mohale's Hoek",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died 2021. First Mosotho cardinal."},
    {"name": "Ernest Simoni", "country": "Albania", "region": "Europe", "born": "1928-10-18", "age": 97, "elector": False,
     "appointed_by": "Francis", "created_at": "2016-11-19", "role": "Honorific (Albanian persecution survivor)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Survived communist-era torture; named cardinal late in life."},

    # ── 4th Francis consistory: 2017-06-28 ──
    {"name": "Jean Zerbo", "country": "Mali", "region": "Africa", "born": "1943-12-27", "age": 82, "elector": False,
     "appointed_by": "Francis", "created_at": "2017-06-28", "role": "Archbishop emeritus of Bamako",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2023."},
    {"name": "Juan José Omella", "country": "Spain", "region": "Europe", "born": "1946-04-21", "age": 79, "elector": True,
     "appointed_by": "Francis", "created_at": "2017-06-28", "role": "Archbishop of Barcelona",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Former president of the Spanish bishops' conference."},
    {"name": "Anders Arborelius", "country": "Sweden", "region": "Europe", "born": "1949-09-24", "age": 76, "elector": True,
     "appointed_by": "Francis", "created_at": "2017-06-28", "role": "Bishop of Stockholm",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Carmelite; first Swedish-born cardinal since the Reformation."},
    {"name": "Louis-Marie Ling Mangkhanekhoun", "country": "Laos", "region": "Asia-Pacific", "born": "1944-04-08", "age": 81, "elector": False,
     "appointed_by": "Francis", "created_at": "2017-06-28", "role": "Apostolic Vicar of Vientiane",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "First Laotian cardinal; aged out 2024."},
    {"name": "Gregorio Rosa Chávez", "country": "El Salvador", "region": "Latin America", "born": "1942-09-03", "age": 83, "elector": False,
     "appointed_by": "Francis", "created_at": "2017-06-28", "role": "Auxiliary Bishop emeritus of San Salvador",
     "wing": "progressive", "papabile_tier": 0, "verified": True,
     "summary": "Close ally of Óscar Romero; aged out."},

    # ── 5th Francis consistory: 2018-06-28 ──
    {"name": "Luis Ladaria Ferrer", "country": "Spain", "region": "Europe", "born": "1944-04-19", "age": 81, "elector": False,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Prefect emeritus, Doctrine of the Faith",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Jesuit; CDF prefect 2017-2023. Aged out."},
    {"name": "Angelo De Donatis", "country": "Italy", "region": "Europe", "born": "1954-01-04", "age": 72, "elector": True,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Major Penitentiary",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Moved from Vicar of Rome (2024)."},
    {"name": "Giovanni Angelo Becciu", "country": "Italy", "region": "Europe", "born": "1948-06-02", "age": 77, "elector": True,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Cardinal (lost rights 2020; restored 2025?)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Convicted in Vatican tribunal 2023 (London property fraud); Francis stripped his cardinal rights in 2020."},
    {"name": "Konrad Krajewski", "country": "Poland", "region": "Europe", "born": "1963-11-25", "age": 62, "elector": True,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Papal Almoner; Prefect, Service of Charity",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Francis's hands-on charity man; goes to homeless camps personally."},
    {"name": "Joseph Coutts", "country": "Pakistan", "region": "Asia-Pacific", "born": "1945-07-21", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Archbishop emeritus of Karachi",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2025."},
    {"name": "António Marto", "country": "Portugal", "region": "Europe", "born": "1947-05-05", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Bishop emeritus of Leiria-Fátima",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Custodian of Fátima."},
    {"name": "Pedro Barreto", "country": "Peru", "region": "Latin America", "born": "1944-02-12", "age": 81, "elector": False,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Archbishop emeritus of Huancayo",
     "wing": "progressive", "papabile_tier": 0, "verified": True,
     "summary": "Jesuit; Amazon-synod voice. Aged out."},
    {"name": "Désiré Tsarahazana", "country": "Madagascar", "region": "Africa", "born": "1954-06-13", "age": 71, "elector": True,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Archbishop of Toamasina",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "First Madagascan cardinal in current generation."},
    {"name": "Giuseppe Petrocchi", "country": "Italy", "region": "Europe", "born": "1948-08-19", "age": 77, "elector": True,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Archbishop emeritus of L'Aquila",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "L'Aquila — quake-stricken see."},
    {"name": "Thomas Aquinas Manyo Maeda", "country": "Japan", "region": "Asia-Pacific", "born": "1949-03-03", "age": 76, "elector": True,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Archbishop of Osaka-Takamatsu",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Japanese voice; small but historically rooted church."},
    {"name": "Sergio Obeso Rivera", "country": "Mexico", "region": "Latin America", "born": "1931-10-31", "age": 94, "elector": False,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Honorific (Archbishop emeritus of Xalapa)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died 2019."},
    {"name": "Toribio Ticona Porco", "country": "Bolivia", "region": "Latin America", "born": "1937-04-25", "age": 88, "elector": False,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Honorific (Bishop emeritus of Corocoro)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aymara indigenous; aged out."},
    {"name": "Aquilino Bocos Merino", "country": "Spain", "region": "Europe", "born": "1938-05-17", "age": 87, "elector": False,
     "appointed_by": "Francis", "created_at": "2018-06-28", "role": "Honorific (Claretian theologian)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},

    # ── 6th Francis consistory: 2019-10-05 ──
    {"name": "Miguel Ángel Ayuso Guixot", "country": "Spain", "region": "Europe", "born": "1952-06-17", "age": 73, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Prefect, Dicastery for Interreligious Dialogue",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Comboni missionary; expert in Christian-Muslim relations."},
    {"name": "José Tolentino Mendonça", "country": "Portugal", "region": "Europe", "born": "1965-12-15", "age": 60, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Prefect, Dicastery for Culture and Education",
     "wing": "progressive", "papabile_tier": 2, "verified": True,
     "summary": "Poet-theologian; one of the youngest Francis cardinals. Rising profile."},
    {"name": "Ignatius Suharyo Hardjoatmodjo", "country": "Indonesia", "region": "Asia-Pacific", "born": "1950-07-09", "age": 75, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Archbishop of Jakarta",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Operates church in world's largest Muslim-majority country."},
    {"name": "Juan García Rodríguez", "country": "Cuba", "region": "Latin America", "born": "1948-07-11", "age": 77, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Archbishop emeritus of Havana",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Cuban church under communist regime."},
    {"name": "Fridolin Ambongo Besungu", "country": "DR Congo", "region": "Africa", "born": "1960-01-24", "age": 65, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Archbishop of Kinshasa",
     "wing": "conservative", "papabile_tier": 2, "verified": True,
     "summary": "Led the African bishops' rejection of Fiducia Supplicans (2024). Articulate, with international profile."},
    {"name": "Jean-Claude Höllerich", "country": "Luxembourg", "region": "Europe", "born": "1958-08-09", "age": 67, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Archbishop of Luxembourg; Relator General, Synod on Synodality",
     "wing": "progressive", "papabile_tier": 2, "verified": True,
     "summary": "Jesuit; relator of the 2021-24 Synod on Synodality."},
    {"name": "Álvaro Ramazzini", "country": "Guatemala", "region": "Latin America", "born": "1947-07-16", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Bishop of Huehuetenango",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Indigenous-rights and migration advocate."},
    {"name": "Matteo Maria Zuppi", "country": "Italy", "region": "Europe", "born": "1955-10-11", "age": 70, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Archbishop of Bologna; President of CEI",
     "wing": "progressive", "papabile_tier": 3, "verified": True,
     "summary": "Sant'Egidio veteran. Francis's peace envoy to Ukraine, Russia, Beijing. The 'Italian Francis'."},
    {"name": "Cristóbal López Romero", "country": "Spain / Morocco", "region": "Africa", "born": "1952-05-19", "age": 73, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Archbishop of Rabat",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Salesian Spaniard serving Morocco's tiny Catholic minority."},
    {"name": "Michael Czerny", "country": "Canada / Czech Republic", "region": "North America", "born": "1946-07-18", "age": 79, "elector": True,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Prefect, Dicastery for Promoting Integral Human Development",
     "wing": "progressive", "papabile_tier": 2, "verified": True,
     "summary": "Jesuit; Francis's lead on migration. Authored chunks of Laudato Si'."},
    {"name": "Eugenio Dal Corso", "country": "Italy / Angola", "region": "Europe", "born": "1939-05-16", "age": 86, "elector": False,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Honorific (Bishop emeritus of Benguela)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Sigitas Tamkevičius", "country": "Lithuania", "region": "Europe", "born": "1938-11-07", "age": 87, "elector": False,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Honorific (Archbishop emeritus of Kaunas; Soviet-era persecution survivor)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Jesuit; jailed in Soviet camps."},
    {"name": "Michael Louis Fitzgerald", "country": "United Kingdom", "region": "Europe", "born": "1937-08-17", "age": 88, "elector": False,
     "appointed_by": "Francis", "created_at": "2019-10-05", "role": "Honorific (Interreligious Dialogue veteran)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Specialist in Christian-Muslim dialogue."},

    # ── 7th Francis consistory: 2020-11-28 ──
    {"name": "Marcello Semeraro", "country": "Italy", "region": "Europe", "born": "1947-12-22", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Prefect, Dicastery for the Causes of Saints",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Long-time Francis ally; secretary of his Council of Cardinals."},
    {"name": "Mario Grech", "country": "Malta", "region": "Europe", "born": "1957-02-20", "age": 68, "elector": True,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Secretary General of the Synod of Bishops",
     "wing": "progressive", "papabile_tier": 2, "verified": True,
     "summary": "Runs the Synod on Synodality — Francis's signature governance reform."},
    {"name": "Antoine Kambanda", "country": "Rwanda", "region": "Africa", "born": "1958-11-10", "age": 67, "elector": True,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Archbishop of Kigali",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "First Rwandan cardinal; survived the 1994 genocide."},
    {"name": "Wilton Gregory", "country": "United States", "region": "North America", "born": "1947-12-07", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Archbishop emeritus of Washington",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "First African-American cardinal; navigated the McCarrick aftermath."},
    {"name": "Jose Advincula", "country": "Philippines", "region": "Asia-Pacific", "born": "1952-03-30", "age": 73, "elector": True,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Archbishop of Manila",
     "wing": "moderate", "papabile_tier": 2, "verified": True,
     "summary": "Heads the largest Catholic archdiocese in Asia."},
    {"name": "Celestino Aós Braco", "country": "Spain / Chile", "region": "Latin America", "born": "1945-04-06", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Archbishop emeritus of Santiago de Chile",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Capuchin; aged out 2025."},
    {"name": "Cornelius Sim", "country": "Brunei", "region": "Asia-Pacific", "born": "1951-09-16", "age": 70, "elector": False,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Apostolic Vicar of Brunei",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "First and only Bruneian cardinal. Died May 2021."},
    {"name": "Augusto Paolo Lojudice", "country": "Italy", "region": "Europe", "born": "1964-07-01", "age": 61, "elector": True,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Archbishop of Siena-Colle di Val d'Elsa-Montalcino",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Roman pastoral background; close to Francis."},
    {"name": "Mauro Gambetti", "country": "Italy", "region": "Europe", "born": "1965-10-27", "age": 60, "elector": True,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Archpriest of St Peter's Basilica",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Franciscan Conventual; manages the Vatican basilica."},
    {"name": "Felipe Arizmendi Esquivel", "country": "Mexico", "region": "Latin America", "born": "1940-05-01", "age": 85, "elector": False,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Honorific (Bishop emeritus of San Cristóbal)",
     "wing": "progressive", "papabile_tier": 0, "verified": True,
     "summary": "Indigenous-pastoral focus."},
    {"name": "Silvano Tomasi", "country": "Italy", "region": "Europe", "born": "1940-10-12", "age": 85, "elector": False,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Honorific (Vatican diplomat)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Long UN diplomat; Sovereign Order of Malta delegate."},
    {"name": "Raniero Cantalamessa", "country": "Italy", "region": "Europe", "born": "1934-07-22", "age": 91, "elector": False,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Honorific (Preacher of the Papal Household)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Capuchin; preacher to the papal household since 1980."},
    {"name": "Enrico Feroci", "country": "Italy", "region": "Europe", "born": "1940-08-27", "age": 85, "elector": False,
     "appointed_by": "Francis", "created_at": "2020-11-28", "role": "Honorific (Caritas Rome)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},

    # ── 8th Francis consistory: 2022-08-27 ──
    {"name": "Arthur Roche", "country": "United Kingdom", "region": "Europe", "born": "1950-03-06", "age": 75, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Prefect, Dicastery for Divine Worship",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Restricts the traditional Latin Mass; nemesis of the Latin Mass community."},
    {"name": "Lazzaro You Heung-sik", "country": "South Korea", "region": "Asia-Pacific", "born": "1951-11-17", "age": 74, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Prefect, Dicastery for the Clergy",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Korean curialist; manages global priestly formation."},
    {"name": "Fernando Vérgez Alzaga", "country": "Spain", "region": "Europe", "born": "1945-03-01", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "President emeritus, Vatican City State",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out 2025."},
    {"name": "Jean-Marc Aveline", "country": "France", "region": "Europe", "born": "1958-12-26", "age": 67, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Marseille",
     "wing": "progressive", "papabile_tier": 2, "verified": True,
     "summary": "Algerian-born; Francis-style focus on migration and the Mediterranean. Quiet but rising."},
    {"name": "Peter Okpaleke", "country": "Nigeria", "region": "Africa", "born": "1963-03-01", "age": 62, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Bishop of Ekwulobia",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Nigerian; consolation pick after his appointment to Ahiara was blocked by clergy."},
    {"name": "Leonardo Steiner", "country": "Brazil", "region": "Latin America", "born": "1950-11-06", "age": 75, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Manaus",
     "wing": "progressive", "papabile_tier": 2, "verified": True,
     "summary": "Francis-aligned; Amazon focus, key in Synod on Amazon."},
    {"name": "Filipe Neri Ferrão", "country": "India", "region": "Asia-Pacific", "born": "1953-01-20", "age": 72, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Goa and Daman",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Heads the historic Padroado see."},
    {"name": "Robert McElroy", "country": "United States", "region": "North America", "born": "1954-02-05", "age": 71, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Washington",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Moved from San Diego to Washington 2025."},
    {"name": "Virgílio do Carmo da Silva", "country": "East Timor", "region": "Asia-Pacific", "born": "1967-11-27", "age": 58, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Díli",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Salesian; first East Timorese cardinal."},
    {"name": "Oscar Cantoni", "country": "Italy", "region": "Europe", "born": "1950-09-01", "age": 75, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Bishop emeritus of Como",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Northern Italian see."},
    {"name": "Anthony Poola", "country": "India", "region": "Asia-Pacific", "born": "1961-11-15", "age": 64, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Hyderabad",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "India's first Dalit cardinal."},
    {"name": "Paulo Cezar Costa", "country": "Brazil", "region": "Latin America", "born": "1967-07-20", "age": 58, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Brasília",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Among the younger Brazilian electors."},
    {"name": "Richard Kuuia Baawobr", "country": "Ghana", "region": "Africa", "born": "1959-06-21", "age": 63, "elector": False,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Bishop of Wa",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died November 2022 — less than 3 months after consistory."},
    {"name": "William Goh", "country": "Singapore", "region": "Asia-Pacific", "born": "1957-06-25", "age": 68, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Singapore",
     "wing": "conservative", "papabile_tier": 1, "verified": True,
     "summary": "First Singaporean cardinal."},
    {"name": "Adalberto Martínez Flores", "country": "Paraguay", "region": "Latin America", "born": "1951-07-08", "age": 74, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Archbishop of Asunción",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "First Paraguayan cardinal."},
    {"name": "Giorgio Marengo", "country": "Italy / Mongolia", "region": "Asia-Pacific", "born": "1974-06-07", "age": 51, "elector": True,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Apostolic Prefect of Ulaanbaatar",
     "wing": "moderate", "papabile_tier": 2, "verified": True,
     "summary": "Youngest cardinal at creation. Consolata missionary in Mongolia."},
    {"name": "Jorge Enrique Jiménez Carvajal", "country": "Colombia", "region": "Latin America", "born": "1942-02-17", "age": 83, "elector": False,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Honorific (Archbishop emeritus of Cartagena)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Lucas Van Looy", "country": "Belgium", "region": "Europe", "born": "1941-09-28", "age": 84, "elector": False,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Honorific (Bishop emeritus of Ghent)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Salesian; declined the red hat initially over abuse-handling criticism."},
    {"name": "Arrigo Miglio", "country": "Italy", "region": "Europe", "born": "1942-07-18", "age": 83, "elector": False,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Honorific (Archbishop emeritus of Cagliari)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Gianfranco Ghirlanda", "country": "Italy", "region": "Europe", "born": "1942-07-05", "age": 83, "elector": False,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Honorific (Jesuit canon lawyer)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Drafted parts of Praedicate Evangelium (Curia reform)."},
    {"name": "Fortunato Frezza", "country": "Italy", "region": "Europe", "born": "1942-02-06", "age": 83, "elector": False,
     "appointed_by": "Francis", "created_at": "2022-08-27", "role": "Honorific (St Peter's basilica canon)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},

    # ── 9th Francis consistory: 2023-09-30 ──
    {"name": "Robert Prevost", "country": "United States", "region": "North America", "born": "1955-09-14", "age": 70, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Prefect, Dicastery for Bishops",
     "wing": "moderate", "papabile_tier": 3, "verified": True,
     "summary": "Augustinian; long mission in Peru. Picks all the world's bishops — most influential curial post."},
    {"name": "Claudio Gugerotti", "country": "Italy", "region": "Europe", "born": "1955-10-07", "age": 70, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Prefect, Dicastery for the Eastern Churches",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Career diplomat; Eastern-rite specialist."},
    {"name": "Víctor Manuel Fernández", "country": "Argentina", "region": "Latin America", "born": "1962-07-18", "age": 63, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Prefect, Dicastery for the Doctrine of the Faith",
     "wing": "progressive", "papabile_tier": 2, "verified": True,
     "summary": "'Tucho' — Francis's theological ghost-writer. Authored Fiducia Supplicans (2023, same-sex blessings)."},
    {"name": "Emil Paul Tscherrig", "country": "Switzerland", "region": "Europe", "born": "1947-02-08", "age": 79, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Apostolic Nuncio emeritus",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Long Vatican diplomat; nuncio to Italy until 2024."},
    {"name": "Christophe Pierre", "country": "France", "region": "Europe", "born": "1946-01-30", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Apostolic Nuncio to the United States",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Senior diplomat; aged out 2026."},
    {"name": "Pierbattista Pizzaballa", "country": "Italy", "region": "Europe", "born": "1965-04-21", "age": 60, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Latin Patriarch of Jerusalem",
     "wing": "moderate", "papabile_tier": 3, "verified": True,
     "summary": "Franciscan; learned Hebrew + Arabic, navigates Holy Land conflict."},
    {"name": "Stephen Brislin", "country": "South Africa", "region": "Africa", "born": "1956-09-24", "age": 69, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Archbishop of Johannesburg",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Moved from Cape Town to Johannesburg 2024."},
    {"name": "Ángel Sixto Rossi", "country": "Argentina", "region": "Latin America", "born": "1958-08-11", "age": 67, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Archbishop of Córdoba",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Jesuit; longtime friend of Francis."},
    {"name": "Luis José Rueda Aparicio", "country": "Colombia", "region": "Latin America", "born": "1962-03-03", "age": 63, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Archbishop of Bogotá; Primate of Colombia",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Primate of Colombia."},
    {"name": "Grzegorz Ryś", "country": "Poland", "region": "Europe", "born": "1964-02-09", "age": 61, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Archbishop of Łódź",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Bridge figure between Polish church and Francis-style reform."},
    {"name": "Stephen Ameyu Martin Mulla", "country": "South Sudan", "region": "Africa", "born": "1964-01-08", "age": 61, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Archbishop of Juba",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "First South Sudanese cardinal."},
    {"name": "José Cobo Cano", "country": "Spain", "region": "Europe", "born": "1965-09-20", "age": 60, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Archbishop of Madrid",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Replaced Osoro in Madrid."},
    {"name": "Protase Rugambwa", "country": "Tanzania", "region": "Africa", "born": "1960-05-31", "age": 65, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Archbishop of Tabora",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Former Curia evangelization secretary."},
    {"name": "Sebastian Francis", "country": "Malaysia", "region": "Asia-Pacific", "born": "1951-02-11", "age": 75, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Bishop of Penang",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Malaysian Tamil-language minority."},
    {"name": "Stephen Chow", "country": "Hong Kong", "region": "Asia-Pacific", "born": "1959-08-07", "age": 66, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Bishop of Hong Kong",
     "wing": "moderate", "papabile_tier": 2, "verified": True,
     "summary": "Jesuit; navigates China-Vatican relations and Hong Kong."},
    {"name": "Américo Aguiar", "country": "Portugal", "region": "Europe", "born": "1973-12-12", "age": 52, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Bishop of Setúbal",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "One of the youngest electors. Hosted WYD Lisbon 2023 logistics."},
    {"name": "François-Xavier Bustillo", "country": "France / Spain", "region": "Europe", "born": "1968-11-23", "age": 57, "elector": True,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Bishop of Ajaccio (Corsica)",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Franciscan Conventual; Spanish-born; pastoral Corsican focus."},
    {"name": "Diego Padrón Sánchez", "country": "Venezuela", "region": "Latin America", "born": "1939-05-04", "age": 86, "elector": False,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Honorific (Archbishop emeritus of Cumaná)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Agostino Marchetto", "country": "Italy", "region": "Europe", "born": "1940-08-28", "age": 85, "elector": False,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Honorific (Curia veteran)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Vatican II historian, Francis-praised theologian."},
    {"name": "Luis Pascual Dri", "country": "Argentina", "region": "Latin America", "born": "1927-04-17", "age": 98, "elector": False,
     "appointed_by": "Francis", "created_at": "2023-09-30", "role": "Honorific (Buenos Aires confessor)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Capuchin centenarian confessor honored by Francis."},
    {"name": "Ángelo Amato", "country": "Italy", "region": "Europe", "born": "1938-06-08", "age": 87, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2014-02-22", "role": "Prefect emeritus, Causes of Saints",
     "wing": "moderate", "papabile_tier": 0, "verified": False,
     "summary": "Note: actually created cardinal by Benedict XVI in 2010, not Francis. Listed for completeness."},

    # ── 10th Francis consistory: 2024-12-07 ──
    {"name": "Carlos Gustavo Castillo Mattasoglio", "country": "Peru", "region": "Latin America", "born": "1950-02-28", "age": 75, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Lima",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Liberation-theology-aligned; replaced conservative Cipriani."},
    {"name": "Vicente Bokalic Iglic", "country": "Argentina", "region": "Latin America", "born": "1952-06-11", "age": 73, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Santiago del Estero",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Lazarist; recently elevated archdiocese."},
    {"name": "Luis Gerardo Cabrera Herrera", "country": "Ecuador", "region": "Latin America", "born": "1955-10-11", "age": 70, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Guayaquil",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Franciscan; Ecuador's first Guayaquil cardinal."},
    {"name": "Fernando Natalio Chomalí Garib", "country": "Chile", "region": "Latin America", "born": "1957-04-15", "age": 68, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Santiago de Chile",
     "wing": "conservative", "papabile_tier": 1, "verified": True,
     "summary": "Lebanese-Chilean; bioethicist."},
    {"name": "Tarcisio Isao Kikuchi", "country": "Japan", "region": "Asia-Pacific", "born": "1958-11-01", "age": 67, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Tokyo",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Divine Word missionary; head of Caritas Internationalis."},
    {"name": "Pablo Virgilio David", "country": "Philippines", "region": "Asia-Pacific", "born": "1959-03-02", "age": 66, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Bishop of Kalookan",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Vocal Duterte-drug-war critic; president of CBCP."},
    {"name": "Ladislav Němet", "country": "Serbia", "region": "Europe", "born": "1956-09-07", "age": 69, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Belgrade",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Divine Word missionary; first Serbian cardinal."},
    {"name": "Jaime Spengler", "country": "Brazil", "region": "Latin America", "born": "1960-09-06", "age": 65, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Porto Alegre; President of CELAM",
     "wing": "moderate", "papabile_tier": 2, "verified": True,
     "summary": "Heads the Latin American bishops' council (2023-2027)."},
    {"name": "Mykola Bychok", "country": "Ukraine / Australia", "region": "Asia-Pacific", "born": "1980-02-13", "age": 45, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Eparch, Sts Peter and Paul Melbourne (Ukrainian Greek Catholic)",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Youngest cardinal at creation (45); Ukrainian Greek Catholic in Australia."},
    {"name": "Frank Leo", "country": "Canada", "region": "North America", "born": "1971-06-30", "age": 54, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Toronto",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Among the youngest electors."},
    {"name": "Domenico Battaglia", "country": "Italy", "region": "Europe", "born": "1963-01-20", "age": 63, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Naples",
     "wing": "progressive", "papabile_tier": 2, "verified": True,
     "summary": "'Don Mimmo' — Francis-style pastoral; quietly papabile."},
    {"name": "Ignace Bessi Dogbo", "country": "Côte d'Ivoire", "region": "Africa", "born": "1961-07-04", "age": 64, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Abidjan",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Replaced aged-out Kutwa."},
    {"name": "Roberto Repole", "country": "Italy", "region": "Europe", "born": "1967-01-29", "age": 59, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Archbishop of Turin",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Theologian; Turin pastoral."},
    {"name": "Baldassare Reina", "country": "Italy", "region": "Europe", "born": "1970-11-26", "age": 55, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Vicar of Rome",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Among the youngest Italian electors; Vicar of Rome."},
    {"name": "Timothy Radcliffe", "country": "United Kingdom", "region": "Europe", "born": "1945-08-22", "age": 80, "elector": False,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Honorific (Dominican; Synod theologian)",
     "wing": "progressive", "papabile_tier": 0, "verified": True,
     "summary": "Former Master of the Dominicans; Synod on Synodality theologian. Aged out almost immediately."},
    {"name": "Fabio Baggio", "country": "Italy", "region": "Europe", "born": "1965-01-22", "age": 60, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Under-Sec., Migrants & Refugees Section",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Scalabrinian; Francis's migration adviser."},
    {"name": "Rolandas Makrickas", "country": "Lithuania", "region": "Europe", "born": "1972-08-31", "age": 53, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Coadjutor Archpriest, Santa Maria Maggiore",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Curia rising star; among youngest electors."},
    {"name": "George Jacob Koovakad", "country": "India", "region": "Asia-Pacific", "born": "1973-08-11", "age": 52, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Prefect, Dicastery for Interreligious Dialogue (2025-)",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Syro-Malabar; Francis's travel organiser turned dicastery prefect."},
    {"name": "Angelo Acerbi", "country": "Italy", "region": "Europe", "born": "1925-09-23", "age": 100, "elector": False,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Honorific (Vatican diplomat)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Centenarian; symbolic recognition."},
    {"name": "Jaime Outeiriño Fernández", "country": "Spain", "region": "Europe", "born": "1947-06-27", "age": 78, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Honorific / regional",
     "wing": "moderate", "papabile_tier": 0, "verified": False,
     "summary": "Entry approximated; verify against Vatican Press Office."},
    {"name": "Paskalis Bruno Syukur", "country": "Indonesia", "region": "Asia-Pacific", "born": "1962-03-17", "age": 63, "elector": True,
     "appointed_by": "Francis", "created_at": "2024-12-07", "role": "Bishop of Bogor",
     "wing": "moderate", "papabile_tier": 1, "verified": False,
     "summary": "Note: Syukur reportedly declined the red hat in 2024 — verify status before relying."},

    # ═════════════════════════════════════════════════════════════════════════
    # BENEDICT XVI (Pope 2005-2013, ~90 cardinals created; ~25 still electors)
    # ═════════════════════════════════════════════════════════════════════════

    # ── Benedict consistories: significant living electors ──
    {"name": "Marc Ouellet", "country": "Canada", "region": "North America", "born": "1944-06-08", "age": 81, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2003-10-21", "role": "Prefect emeritus, Bishops",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Was 2013 papabile. CDF predecessor. Aged out 2024."},
    {"name": "Péter Erdő", "country": "Hungary", "region": "Europe", "born": "1952-06-25", "age": 73, "elector": True,
     "appointed_by": "John Paul II", "created_at": "2003-10-21", "role": "Archbishop of Esztergom-Budapest",
     "wing": "conservative", "papabile_tier": 3, "verified": True,
     "summary": "Canon lawyer; top conservative papabile. Was relator at two Synods. The 'continuity-with-Benedict' candidate."},
    {"name": "Sean O'Malley", "country": "United States", "region": "North America", "born": "1944-06-29", "age": 81, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2006-03-24", "role": "Archbishop emeritus of Boston",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Capuchin; ran the Pontifical Commission for the Protection of Minors. Aged out 2024."},
    {"name": "Stanisław Dziwisz", "country": "Poland", "region": "Europe", "born": "1939-04-27", "age": 86, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2006-03-24", "role": "Archbishop emeritus of Kraków",
     "wing": "conservative", "papabile_tier": 0, "verified": True,
     "summary": "John Paul II's longtime personal secretary."},
    {"name": "Christoph Schönborn", "country": "Austria", "region": "Europe", "born": "1945-01-22", "age": 80, "elector": False,
     "appointed_by": "John Paul II", "created_at": "1998-02-21", "role": "Archbishop emeritus of Vienna",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Catechism of the Catholic Church editor; aged out as elector 2025."},
    {"name": "Reinhard Marx", "country": "Germany", "region": "Europe", "born": "1953-09-21", "age": 72, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2010-11-20", "role": "Archbishop of Munich and Freising",
     "wing": "progressive", "papabile_tier": 1, "verified": True,
     "summary": "Was a 2013 papabile. Has offered resignation over abuse handling. Drives the German Synodal Way."},
    {"name": "Robert Sarah", "country": "Guinea", "region": "Africa", "born": "1945-06-15", "age": 80, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2010-11-20", "role": "Prefect emeritus, Divine Worship",
     "wing": "traditional", "papabile_tier": 2, "verified": True,
     "summary": "Traditionalist hero; Latin Mass advocate. Aged out 2025."},
    {"name": "Donald Wuerl", "country": "United States", "region": "North America", "born": "1940-11-12", "age": 85, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2010-11-20", "role": "Archbishop emeritus of Washington",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Resigned 2018 amid McCarrick aftermath; aged out."},
    {"name": "Raymond Burke", "country": "United States", "region": "North America", "born": "1948-06-30", "age": 77, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2010-11-20", "role": "Patron emeritus, Order of Malta",
     "wing": "traditional", "papabile_tier": 1, "verified": True,
     "summary": "Most vocal traditionalist critic of Francis among electors. Latin Mass advocate."},
    {"name": "Timothy Dolan", "country": "United States", "region": "North America", "born": "1950-02-06", "age": 75, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2012-02-18", "role": "Archbishop of New York",
     "wing": "conservative", "papabile_tier": 2, "verified": True,
     "summary": "Most-recognised US bishop; conservative, but pragmatic."},
    {"name": "Daniel DiNardo", "country": "United States", "region": "North America", "born": "1949-05-23", "age": 76, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2007-11-24", "role": "Archbishop of Galveston-Houston",
     "wing": "conservative", "papabile_tier": 1, "verified": True,
     "summary": "Former USCCB president."},
    {"name": "Willem Eijk", "country": "Netherlands", "region": "Europe", "born": "1953-06-22", "age": 72, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2012-02-18", "role": "Archbishop of Utrecht",
     "wing": "conservative", "papabile_tier": 1, "verified": True,
     "summary": "Bioethicist; conservative."},
    {"name": "Luis Antonio Tagle", "country": "Philippines", "region": "Asia-Pacific", "born": "1957-06-21", "age": 68, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2012-11-24", "role": "Pro-Prefect, Dicastery for Evangelization",
     "wing": "progressive", "papabile_tier": 3, "verified": True,
     "summary": "'The Asian Francis'. Long-discussed papabile; reputation dented by Caritas mismanagement (2022)."},
    {"name": "John Onaiyekan", "country": "Nigeria", "region": "Africa", "born": "1944-01-29", "age": 81, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2012-11-24", "role": "Archbishop emeritus of Abuja",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Long-respected voice; aged out."},
    {"name": "Bechara Boutros Raï", "country": "Lebanon", "region": "Middle East", "born": "1940-02-25", "age": 86, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2012-11-24", "role": "Maronite Patriarch of Antioch",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Maronite Catholic Patriarch."},
    {"name": "Béchara Raï (Bechara)", "country": "Lebanon", "region": "Middle East", "born": "1940-02-25", "age": 86, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2012-11-24", "role": "(duplicate — see above)",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "(duplicate)"},
    {"name": "Joseph Zen Ze-kiun", "country": "Hong Kong", "region": "Asia-Pacific", "born": "1932-01-13", "age": 93, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2006-03-24", "role": "Bishop emeritus of Hong Kong",
     "wing": "traditional", "papabile_tier": 0, "verified": True,
     "summary": "China-Vatican deal critic; subject of 2022 Hong Kong national security trial."},
    {"name": "Ricardo Vidal", "country": "Philippines", "region": "Asia-Pacific", "born": "1931-02-06", "age": 95, "elector": False,
     "appointed_by": "John Paul II", "created_at": "1985-05-25", "role": "Archbishop emeritus of Cebu",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Died 2017. Listed for completeness."},
    {"name": "George Pell", "country": "Australia", "region": "Asia-Pacific", "born": "1941-06-08", "age": 81, "elector": False,
     "appointed_by": "John Paul II", "created_at": "2003-10-21", "role": "Prefect emeritus, Economy",
     "wing": "conservative", "papabile_tier": 0, "verified": True,
     "summary": "Died Jan 2023. Convicted 2018 then acquitted 2020 on appeal."},
    {"name": "Tarcisio Bertone", "country": "Italy", "region": "Europe", "born": "1934-12-02", "age": 91, "elector": False,
     "appointed_by": "John Paul II", "created_at": "2003-10-21", "role": "Secretary of State emeritus",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Salesian; Sec State under Benedict XVI."},
    {"name": "Walter Kasper", "country": "Germany", "region": "Europe", "born": "1933-03-05", "age": 92, "elector": False,
     "appointed_by": "John Paul II", "created_at": "2001-02-21", "role": "President emeritus, Christian Unity",
     "wing": "progressive", "papabile_tier": 0, "verified": True,
     "summary": "Ecumenical theologian; long retired but influential."},
    {"name": "Angelo Bagnasco", "country": "Italy", "region": "Europe", "born": "1943-01-14", "age": 82, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2007-11-24", "role": "Archbishop emeritus of Genoa",
     "wing": "conservative", "papabile_tier": 1, "verified": True,
     "summary": "Former CEI president; voice of Italian traditionalists."},
    {"name": "Angelo Comastri", "country": "Italy", "region": "Europe", "born": "1943-09-17", "age": 82, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2007-11-24", "role": "Archpriest emeritus, St Peter's",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Sean Brady", "country": "Ireland", "region": "Europe", "born": "1939-08-16", "age": 86, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2007-11-24", "role": "Archbishop emeritus of Armagh",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Jean-Pierre Ricard", "country": "France", "region": "Europe", "born": "1944-09-25", "age": 81, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2006-03-24", "role": "Archbishop emeritus of Bordeaux",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out. Admitted 1980s abuse, declined to fully exercise rights."},
    {"name": "Giuseppe Betori", "country": "Italy", "region": "Europe", "born": "1947-02-25", "age": 78, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2012-02-18", "role": "Archbishop emeritus of Florence",
     "wing": "conservative", "papabile_tier": 1, "verified": True,
     "summary": "Biblical scholar; one of the leading Italian conservatives."},
    {"name": "Odilo Pedro Scherer", "country": "Brazil", "region": "Latin America", "born": "1949-09-21", "age": 76, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2007-11-24", "role": "Archbishop emeritus of São Paulo",
     "wing": "conservative", "papabile_tier": 1, "verified": True,
     "summary": "Was a 2013 papabile; vote-getter in the first ballots that year."},
    {"name": "Oswald Gracias", "country": "India", "region": "Asia-Pacific", "born": "1944-12-24", "age": 81, "elector": False,
     "appointed_by": "Benedict XVI", "created_at": "2007-11-24", "role": "Archbishop emeritus of Bombay",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Council of Cardinals member under Francis; aged out 2024."},
    {"name": "Cleemis Baselios Thottunkal", "country": "India", "region": "Asia-Pacific", "born": "1959-06-15", "age": 66, "elector": True,
     "appointed_by": "Benedict XVI", "created_at": "2012-11-24", "role": "Major Archbishop, Syro-Malankara Catholic Church",
     "wing": "moderate", "papabile_tier": 1, "verified": True,
     "summary": "Heads the Syro-Malankara sui-iuris church."},
    {"name": "Peter Turkson", "country": "Ghana", "region": "Africa", "born": "1948-10-11", "age": 77, "elector": True,
     "appointed_by": "John Paul II", "created_at": "2003-10-21", "role": "Chancellor, Pontifical Academy of Sciences",
     "wing": "moderate", "papabile_tier": 2, "verified": True,
     "summary": "Long-considered the leading African papabile. Former Justice & Peace prefect."},
    {"name": "Wilfrid Fox Napier", "country": "South Africa", "region": "Africa", "born": "1941-03-08", "age": 84, "elector": False,
     "appointed_by": "John Paul II", "created_at": "2001-02-21", "role": "Archbishop emeritus of Durban",
     "wing": "conservative", "papabile_tier": 1, "verified": True,
     "summary": "Vocal conservative; aged out as elector in 2021."},
    {"name": "Norberto Rivera Carrera", "country": "Mexico", "region": "Latin America", "born": "1942-06-06", "age": 83, "elector": False,
     "appointed_by": "John Paul II", "created_at": "1998-02-21", "role": "Archbishop emeritus of Mexico City",
     "wing": "conservative", "papabile_tier": 0, "verified": True,
     "summary": "Aged out."},
    {"name": "Geraldo Majella Agnelo", "country": "Brazil", "region": "Latin America", "born": "1933-10-19", "age": 92, "elector": False,
     "appointed_by": "John Paul II", "created_at": "2001-02-21", "role": "Archbishop emeritus of São Salvador da Bahia",
     "wing": "moderate", "papabile_tier": 0, "verified": True,
     "summary": "Aged out long ago."},
    {"name": "Cláudio Hummes", "country": "Brazil", "region": "Latin America", "born": "1934-08-08", "age": 91, "elector": False,
     "appointed_by": "John Paul II", "created_at": "2001-02-21", "role": "Archbishop emeritus of São Paulo",
     "wing": "progressive", "papabile_tier": 0, "verified": True,
     "summary": "Died July 2022. Whispered 'Don't forget the poor' to Bergoglio at the 2013 conclave."},
]

# Deduplicate by name (a few intentional dupes above for cross-references)
_seen: set[str] = set()
CARDINALS = [c for c in CARDINALS if not (c["name"] in _seen or _seen.add(c["name"]))]


# ─── Papabile priors ────────────────────────────────────────────────────────
# Aggregated Vaticanist consensus + bookmaker odds (Polymarket, Smarkets,
# William Hill conclave markets historically). Priors sum to ~55%, leaving
# ~45% for the field (an under-the-radar cardinal — historically a common
# outcome: Bergoglio 2013, Wojtyła 1978). Treat as a consensus prior, not
# a model output.

PAPABILE_PRIORS = [
    {"name": "Pietro Parolin",          "prior_pct": 11.0, "rationale": "Continuity Secretary of State; default establishment choice."},
    {"name": "Matteo Maria Zuppi",      "prior_pct":  9.0, "rationale": "Francis's peace envoy + Sant'Egidio + Bologna; progressive Italian."},
    {"name": "Luis Antonio Tagle",      "prior_pct":  7.5, "rationale": "'Asian Francis' — but Caritas mismanagement dented his standing."},
    {"name": "Péter Erdő",              "prior_pct":  7.0, "rationale": "Top conservative; canon lawyer; bridge to the Benedict camp."},
    {"name": "Pierbattista Pizzaballa", "prior_pct":  6.0, "rationale": "Holy Land Patriarch; Franciscan; talks of him spiked Oct 2023 onward."},
    {"name": "Robert Prevost",          "prior_pct":  5.0, "rationale": "American but mission-Latin-American; runs bishop selection."},
    {"name": "Fridolin Ambongo Besungu","prior_pct":  3.5, "rationale": "African conservative consensus voice (post-Fiducia)."},
    {"name": "Peter Turkson",           "prior_pct":  2.5, "rationale": "Long-discussed African moderate; age (77) cutting against him."},
    {"name": "Jean-Marc Aveline",       "prior_pct":  2.0, "rationale": "Algerian-born Marseille — Mediterranean / migration profile."},
    {"name": "Mario Grech",             "prior_pct":  1.5, "rationale": "Synod synodality architect; the inside-the-tent reformer."},
    {"name": "Domenico Battaglia",      "prior_pct":  1.5, "rationale": "Naples 'Don Mimmo' — Francis-style pastoral, quietly papabile."},
    {"name": "Jean-Claude Höllerich",   "prior_pct":  1.0, "rationale": "Jesuit Luxembourger; ran the Synod on Synodality."},
    {"name": "Stephen Chow",            "prior_pct":  1.0, "rationale": "Hong Kong + Jesuit — narrow but possible China-track choice."},
    {"name": "Víctor Manuel Fernández", "prior_pct":  0.5, "rationale": "Tucho is too tied to Francis's most contested doctrinal moves."},
    {"name": "Giorgio Marengo",         "prior_pct":  0.5, "rationale": "Mongolia mission cardinal — the surprise outsider Francis favoured creating."},
]


# ─── Rules + aggregate stats ────────────────────────────────────────────────

CONCLAVE_RULES = {
    "max_electors": 120,            # Paul VI's cap in Romano Pontifici Eligendo (1975); Francis routinely exceeded
    "actual_electors_approx": 135,  # rough current count
    "two_thirds_majority": True,    # Universi Dominici Gregis (1996, as amended)
    "voting_age_cutoff": 80,        # under-80 on the day Holy See becomes vacant = elector
    "ballots_per_day": 4,           # after day 1
    "ballots_before_runoff": 33,    # Benedict XVI's 2007 amendment requires 2/3 always
    "regional_blocs": ["Europe", "Latin America", "North America", "Africa", "Asia-Pacific", "Middle East"],
    "field_residual_pct": 40,       # Probability the next pope is NOT in the public papabile shortlist
}

# Rough aggregate breakdown of the FULL ~135-elector college. Numbers
# are publicly cited by the College of Cardinals Report as of late 2024
# (after Francis's 10th consistory). Bump as new cardinals are created
# or die.
COLLEGE_AGGREGATES = {
    "total_cardinals": 252,
    "total_electors":  135,
    "by_region": {
        "Europe":         53,   # historic plurality; shrinking
        "Latin America":  22,
        "Asia-Pacific":   24,
        "Africa":         18,
        "North America":  16,
        "Middle East":     2,
    },
    "by_appointer": {
        "Francis":       109,   # ~80% of electors (created 2014-2024 consistories)
        "Benedict XVI":   23,
        "John Paul II":    3,
    },
    "italian_electors": 17,     # historically the largest national bloc
    "two_thirds_threshold": 90, # if 135 electors; ≥ ceiling(135*2/3) = 90
}
