"""Claude-generated plain-English summaries for public source profiles.

Adds a 3–5 sentence narrative description of each rated source, rendered
on `/sources/{handle}` above the numerical credibility table. Summaries
are generated by Claude Sonnet (nuanced writing matters more than cost
here) and regenerated monthly by a cron job.

Schema:
  - source_summaries: one row per source_handle
"""

revision = "029"
down_revision = "024"


def upgrade(c):
    c.execute("""
        CREATE TABLE IF NOT EXISTS source_summaries (
            id                 INTEGER PRIMARY KEY AUTOINCREMENT,
            source_handle      TEXT NOT NULL UNIQUE,
            summary            TEXT NOT NULL,
            generated_at       INTEGER NOT NULL,
            generated_by       TEXT NOT NULL,
            cache_valid_until  INTEGER NOT NULL,
            predictions_considered INTEGER NOT NULL DEFAULT 0
        )
    """)
    c.execute("CREATE INDEX IF NOT EXISTS idx_source_summaries_handle ON source_summaries(source_handle)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_source_summaries_valid ON source_summaries(cache_valid_until)")


def downgrade(c):
    c.execute("DROP INDEX IF EXISTS idx_source_summaries_valid")
    c.execute("DROP INDEX IF EXISTS idx_source_summaries_handle")
    c.execute("DROP TABLE IF EXISTS source_summaries")
