"""E2E-specific fixtures — gate bypass, invite-token factory, Stripe mocks.

The outer ``tests/conftest.py`` already provides ``client``, ``make_user``,
``authed_user``, ``auth_headers`` etc. Those ride the shared in-memory
DB. This file layers on:

  * ``GATE_TOKEN`` env + a helper that walks a fresh client past the
    site gate so flow tests can continue on to /token, /register, …
  * ``invite_token()`` — mints an unclaimed invite_tokens row the signup
    flow can present at /auth/validate-token
  * ``mock_smtp`` — stashes every enqueue_email call in a list the test
    can inspect
  * ``mock_stripe_webhook()`` — synthesises a signed Stripe webhook
    body + headers for the subscription flow
  * ``freeze_time`` — tiny shim over time.time / datetime.utcnow used
    by the flow tests that need to simulate "hours later"

Nothing here mocks user DB state — every flow runs end-to-end against
the real SQL in the in-memory testdb. That's the whole point of e2e.
"""

from __future__ import annotations

USES_TESTDB = True

import hmac as _hmac
import hashlib as _hashlib
import json as _json
import os as _os
import secrets
import time as _time
from contextlib import contextmanager
from typing import Optional

import pytest

from tests import _testdb  # noqa: F401 — ensures shared db.conn patch
import db


# ── Gate bypass ────────────────────────────────────────────────────────────

# Fixed token so the gate password is predictable across tests. Real env
# has a 32-char secret; tests only need something the middleware accepts.
E2E_GATE_TOKEN = "e2e-gate-token-deterministic"
_os.environ["SITE_ACCESS_TOKEN"] = E2E_GATE_TOKEN
# Prevent the middleware from ALSO requiring hardened prod-only flags.
_os.environ.pop("PRODUCTION", None)


@pytest.fixture
def gate_token() -> str:
    return E2E_GATE_TOKEN


@pytest.fixture
def pass_gate(client, gate_token):
    """Walk a client past the site gate. Returns the same client with
    the gate cookie set so follow-up navigation can proceed.

    Always clears the shared rate-limit store at call time — the gate
    is rate-limited per-IP, and TestClient re-uses 127.0.0.1 for every
    request so back-to-back e2e flows trip the limiter otherwise.
    """
    def _pass():
        try:
            import server as _server
            if hasattr(_server, "_rate_store"):
                _server._rate_store.clear()
            if hasattr(_server, "_login_failures"):
                _server._login_failures.clear()
        except Exception:
            pass
        # Double-submit CSRF: the cookie value and the submitted value
        # must match. Reads whatever token the server already baked into
        # the jar (first-visit GETs get one auto-generated by the
        # middleware) and echoes it back in the form body. If the jar is
        # empty we drop in a deterministic "t" ourselves.
        csrf_val = client.cookies.get("_csrf")
        if not csrf_val:
            csrf_val = "t"
            client.cookies.set("_csrf", csrf_val)
        # The gate handler accepts the form field `token` (see server.py).
        # Form-encoded POSTs read the CSRF token from `_csrf` in the body
        # (server.py::CSRFMiddleware parses the body for the form field
        # rather than consulting the header). JSON POSTs use the
        # x-csrf-token header; forms use the `_csrf` body field.
        r = client.post(
            "/gate",
            data={"token": gate_token, "_csrf": csrf_val},
            follow_redirects=False,
        )
        # 302/303 on success, 200 on invalid (renders the form again).
        assert r.status_code in (302, 303, 200), (
            f"gate bypass failed: {r.status_code} {r.text[:200]}"
        )
        # Some builds set the gate cookie via the middleware chain that the
        # TestClient consumes into .cookies automatically. If the cookie
        # didn't land, inject it directly so downstream requests still
        # look past-gate.
        if "narve_gate_access" not in client.cookies:
            client.cookies.set("narve_gate_access", gate_token)
        return client
    return _pass


# ── Invite token factory ───────────────────────────────────────────────────


@pytest.fixture
def make_invite_token():
    """Create an unclaimed invite_tokens row. Returns the raw token string."""
    def _factory(note: str = "e2e-signup") -> str:
        raw = secrets.token_urlsafe(32)[:32]
        with db.conn() as c:
            c.execute(
                "INSERT INTO invite_tokens (token, status, note, created_at) "
                "VALUES (?, 'unclaimed', ?, ?)",
                (raw, note, int(_time.time())),
            )
        return raw
    return _factory


# ── Outbound email / background-job capture ────────────────────────────────


@pytest.fixture
def mock_smtp(monkeypatch):
    """Every call to jobs.email_jobs.enqueue_email is captured in a list
    the test can inspect. Does NOT block network — EMAIL_DRY_RUN also
    already prevents real sends — but the capture gives us an easier
    assertion point than parsing the dry-run log."""
    sent: list[dict] = []

    async def fake_enqueue(to: str, template: str, context: Optional[dict] = None,
                           tags: Optional[list] = None, **extra):
        sent.append({
            "to": to,
            "template": template,
            "context": dict(context or {}),
            "tags": list(tags or []),
            "extra": extra,
        })
        return {"queued": True, "dry_run": True}

    try:
        import jobs.email_jobs as _ej
        monkeypatch.setattr(_ej, "enqueue_email", fake_enqueue, raising=False)
    except Exception:
        pass
    try:
        import server_features as _sf
        monkeypatch.setattr(_sf, "enqueue_email", fake_enqueue, raising=False)
    except Exception:
        pass
    return sent


@pytest.fixture
def capture_jobs(monkeypatch):
    """Capture every enqueue_job call — useful for asserting that
    the signup flow fires a welcome_email job, the market-mover
    pipeline schedules alerts, etc."""
    jobs_fired: list[dict] = []

    async def fake_enqueue_job(name: str, **kwargs):
        jobs_fired.append({"name": name, "kwargs": dict(kwargs)})
        return f"job-{len(jobs_fired)}"

    for mod_path in ("jobs", "server_features", "server"):
        try:
            mod = __import__(mod_path, fromlist=["enqueue_job"])
            if hasattr(mod, "enqueue_job"):
                monkeypatch.setattr(mod, "enqueue_job", fake_enqueue_job, raising=False)
        except Exception:
            pass
    return jobs_fired


# ── Stripe webhook synthesiser ─────────────────────────────────────────────


@pytest.fixture
def stripe_webhook_secret(monkeypatch):
    secret = "whsec_e2e_deterministic_stripe_secret"
    monkeypatch.setenv("STRIPE_WEBHOOK_SECRET", secret)
    return secret


@pytest.fixture
def mock_stripe_webhook(stripe_webhook_secret):
    """Build (body, headers) for a signed Stripe event. Matches
    helpers.signed_stripe_event() shape but lets flow tests choose the
    event type + payload inline."""
    def _build(event_type: str, data_object: dict,
               *, event_id: Optional[str] = None) -> tuple[str, dict]:
        ev = {
            "id": event_id or f"evt_e2e_{secrets.token_hex(8)}",
            "type": event_type,
            "data": {"object": data_object},
            "created": int(_time.time()),
        }
        body = _json.dumps(ev, separators=(",", ":"))
        ts = str(int(_time.time()))
        sig_payload = f"{ts}.{body}".encode()
        v1 = _hmac.new(
            stripe_webhook_secret.encode(),
            sig_payload,
            _hashlib.sha256,
        ).hexdigest()
        return body, {
            "Stripe-Signature": f"t={ts},v1={v1}",
            "Content-Type": "application/json",
        }
    return _build


# ── Clock control — cheap freezegun alternative ────────────────────────────


@contextmanager
def _patch_time(monkeypatch, ts: int):
    """Patch time.time() and db.int(time.time())-style callers so
    follow-up code thinks `ts` seconds have elapsed since the last
    time.time() read. Does not alter datetime — flows that rely on
    datetime.utcnow need freezegun proper."""
    real = _time.time

    def fake() -> float:
        return float(ts)

    monkeypatch.setattr(_time, "time", fake)
    try:
        yield fake
    finally:
        monkeypatch.setattr(_time, "time", real)


@pytest.fixture
def fast_forward(monkeypatch):
    """Use as::

        with fast_forward(hours=25):
            # server now thinks we're 25 hours in the future
            ...
    """
    @contextmanager
    def _ff(*, seconds: int = 0, minutes: int = 0, hours: int = 0, days: int = 0):
        delta = seconds + 60 * minutes + 3600 * hours + 86400 * days
        target = int(_time.time()) + delta
        with _patch_time(monkeypatch, target):
            yield target
    return _ff


# ── Per-test DB cleanup so flows stay isolated ─────────────────────────────


@pytest.fixture(autouse=True)
def _e2e_clean_slate():
    """Wipe user-scoped tables between flows. The shared in-memory DB
    means state otherwise leaks from one flow's signup into the next
    flow's login. We keep schema-level seed data (source_credibility
    rows etc) so flows that use them don't have to re-seed."""
    # Tables that individual e2e flows write to. Adding a missing table
    # is never an error — SQLite just returns no rows deleted.
    wipeable = (
        "sessions", "invite_tokens", "password_resets",
        "user_market_views", "user_market_alerts",
        "market_movement_events",
        "saved_predictions", "saved_markets", "followed_sources",
        "subscriptions", "user_onboarding",
        "impersonation_actions",
    )
    yield
    try:
        with db.conn() as c:
            for table in wipeable:
                try:
                    c.execute(f"DELETE FROM {table}")
                except Exception:
                    pass
            # users last — FKs from the tables above
            try:
                c.execute("DELETE FROM users WHERE email LIKE '%@test.example' OR email LIKE '%@e2e.test'")
            except Exception:
                pass
    except Exception:
        pass
