"""Claude Sonnet-generated plain-English summaries for rated source profiles.

Each rated source gets a 3–5 sentence narrative rendered on the public
`/sources/{handle}` page, above the numerical credibility breakdown. The
summary is meant to read like something an analyst would write — "this
source is strong on Fed decisions and cautious on crypto" — rather than
a rehash of the numbers, which are already shown in the table below it.

Generated by Claude Sonnet (nuanced writing is worth the higher per-token
cost here), regenerated monthly by a cron job, and cached for 30 days.
Sources with too little data get a graceful fallback string — we never
show an empty card, and we never spend tokens on a source we can't write
anything substantive about.

See db.get_source_summary / db.upsert_source_summary for the cache and
migrations/025_source_summaries.py for the table definition.
"""

from __future__ import annotations

import logging
import time
from typing import Any, Optional

import db

from . import claude_usage


log = logging.getLogger("intelligence.source_summary")


SUMMARY_MAX_TOKENS = 512
SUMMARY_CACHE_TTL_SECONDS = 30 * 86400  # 30 days
MIN_PREDICTIONS_FOR_GENERATION = 5


SUMMARY_SYSTEM_PROMPT = """\
You write short, factual profile summaries for a prediction-market
analytics site. Your audience is a trader deciding whether to trust a
particular source's calls on future events.

Given structured stats about the source, produce 3–5 sentences in plain
English. Mention:
  - what topics they predict on most often
  - their accuracy on tracked predictions
  - any noteworthy strength or weakness visible in the numbers (e.g.
    "strong on Fed decisions", "cautious on crypto")

Do NOT:
  - invent facts not supported by the stats
  - quote their predictions verbatim
  - use bullet points, headers, or markdown — produce flowing prose
  - begin with "This source" — start with "@<handle>" instead
  - add a closing sentence about narve.ai or the dashboard

Keep it concise: 3–5 sentences, ~60–90 words. Output ONLY the prose,
no quotes or metadata.
"""


# ── Context building ─────────────────────────────────────────────────────────


def _build_user_message(
    source_handle: str,
    cred: Any,
    categories: list[Any],
    predictions: list[Any],
) -> str:
    """Assemble the stat blob Claude is asked to summarise."""
    total = int(cred["total_predictions"] or 0)
    correct = int(cred["correct_predictions"] or 0)
    accuracy_pct = round(100 * correct / total, 1) if total else 0.0
    global_cred = round(float(cred["global_credibility"] or 0.5), 3)

    lines: list[str] = [
        f"Source handle: @{source_handle}",
        f"Global credibility: {global_cred}",
        f"Accuracy: {correct}/{total} = {accuracy_pct}%",
        f"Categories active: {int(cred['categories_active'] or 0)}",
    ]

    if categories:
        lines.append("")
        lines.append("Category breakdown:")
        for cat in categories[:10]:
            cat_total = int(cat["prediction_count"] or 0)
            cat_correct = int(cat["correct_count"] or 0)
            cat_cred = round(float(cat["category_credibility"] or 0.5), 3)
            cat_acc = round(100 * cat_correct / cat_total, 1) if cat_total else 0.0
            lines.append(
                f"  - {cat['category']}: credibility={cat_cred}, "
                f"{cat_correct}/{cat_total} correct ({cat_acc}%)"
            )

    if predictions:
        lines.append("")
        lines.append("Recent predictions (most recent first):")
        for p in predictions[:20]:
            content = (p["content"] or "")[:140]
            cat = p["category"] or "other"
            status = "resolved" if p["resolved"] else "open"
            outcome = ""
            if p["resolved"]:
                outcome = " (correct)" if p["resolved_correct"] else " (wrong)"
            lines.append(f"  - [{cat}] {status}{outcome}: {content}")

    return "\n".join(lines)


# ── Claude call (mockable) ───────────────────────────────────────────────────


async def _call_claude(user_message: str) -> tuple[Optional[str], Any]:
    """Single Claude call; tests monkey-patch this."""
    client = claude_usage.get_async_client()
    if client is None:
        return None, None
    try:
        resp = await client.messages.create(
            model=claude_usage.SUMMARISATION_MODEL,
            max_tokens=SUMMARY_MAX_TOKENS,
            system=SUMMARY_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_message}],
        )
    except Exception as exc:
        log.error("source_summary: Claude call failed: %s", exc)
        return None, None

    parts: list[str] = []
    for block in resp.content:
        text = getattr(block, "text", None)
        if text:
            parts.append(text)
    return ("".join(parts) if parts else None), resp


# ── Public entry points ──────────────────────────────────────────────────────


def _graceful_fallback(source_handle: str, total: int) -> str:
    """Short message used when there isn't enough data to summarise. Written
    so the profile card still looks intentional rather than empty.
    """
    if total == 0:
        return (
            f"@{source_handle} has not yet made enough tracked predictions "
            f"for a narrative summary. As their prediction history grows, "
            f"this section will describe their areas of focus and relative strengths."
        )
    return (
        f"@{source_handle} has {total} tracked prediction"
        f"{'s' if total != 1 else ''} on file. A full narrative summary will "
        f"generate once their history passes the threshold for a meaningful "
        f"category-level breakdown."
    )


async def generate_source_summary(
    source_handle: str,
    *,
    force: bool = False,
) -> dict:
    """Return (and cache) a plain-English summary for *source_handle*.

    Order of operations:
      1. If cached row exists and is fresh (and force=False), log a cache
         hit and return the stored summary.
      2. Load credibility stats + category breakdown + recent predictions.
      3. If the source has fewer than MIN_PREDICTIONS_FOR_GENERATION
         predictions, cache a graceful-fallback message (no Claude call).
      4. Otherwise call Claude Sonnet, cache, and return the response.
    """
    handle = source_handle.strip().lstrip("@")
    if not handle:
        return {
            "source_handle": "",
            "summary": "",
            "generated_by": "empty",
            "generated_at": int(time.time()),
            "predictions_considered": 0,
        }

    if not force:
        cached = db.get_source_summary(handle)
        if cached:
            claude_usage.log_response(
                feature="summarisation",
                model=claude_usage.SUMMARISATION_MODEL,
                response=None,
                cached_hit=True,
            )
            return {
                "source_handle": cached["source_handle"],
                "summary": cached["summary"],
                "generated_by": cached["generated_by"],
                "generated_at": cached["generated_at"],
                "predictions_considered": cached["predictions_considered"],
            }

    cred = db.get_source_credibility(handle) if hasattr(db, "get_source_credibility") else None
    if not cred:
        payload = {
            "summary": _graceful_fallback(handle, 0),
            "generated_at": int(time.time()),
            "generated_by": "fallback_no_data",
            "cache_valid_until": int(time.time()) + SUMMARY_CACHE_TTL_SECONDS,
            "predictions_considered": 0,
        }
        db.upsert_source_summary(handle, payload)
        return {"source_handle": handle, **payload}

    categories = db.get_all_category_credibilities(handle) if hasattr(db, "get_all_category_credibilities") else []
    predictions = db.get_source_prediction_context(handle, limit=50)
    total = int(cred["total_predictions"] or 0)

    if total < MIN_PREDICTIONS_FOR_GENERATION:
        payload = {
            "summary": _graceful_fallback(handle, total),
            "generated_at": int(time.time()),
            "generated_by": "fallback_low_data",
            "cache_valid_until": int(time.time()) + SUMMARY_CACHE_TTL_SECONDS,
            "predictions_considered": total,
        }
        db.upsert_source_summary(handle, payload)
        return {"source_handle": handle, **payload}

    user_message = _build_user_message(handle, cred, categories, predictions)
    raw, resp = await _call_claude(user_message)

    if resp is not None:
        claude_usage.log_response(
            feature="summarisation",
            model=claude_usage.SUMMARISATION_MODEL,
            response=resp,
            cached_hit=False,
        )
    else:
        claude_usage.log_failure(
            feature="summarisation",
            model=claude_usage.SUMMARISATION_MODEL,
        )

    summary_text = (raw or "").strip()
    if not summary_text:
        summary_text = _graceful_fallback(handle, total)
        generated_by = "fallback_claude_unavailable"
    else:
        # Defensive length cap: Sonnet occasionally overshoots 5 sentences.
        summary_text = summary_text[:1200]
        generated_by = claude_usage.SUMMARISATION_MODEL

    now = int(time.time())
    payload = {
        "summary": summary_text,
        "generated_at": now,
        "generated_by": generated_by,
        "cache_valid_until": now + SUMMARY_CACHE_TTL_SECONDS,
        "predictions_considered": len(predictions),
    }
    db.upsert_source_summary(handle, payload)
    return {"source_handle": handle, **payload}
